# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-08 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180908_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
